//
//  ClipboardStore.swift
//  Espaste
//

import AppKit
import Combine
import Foundation

class ClipboardStore: ObservableObject {
    static let shared = ClipboardStore()

    @Published private(set) var items: [ClipboardItem] = []

    private let maxItems = 200
    private var lastChangeCount: Int = 0
    private var skipNextChange = false
    private var cancellables = Set<AnyCancellable>()

    // http://nspasteboard.org — apps set these types to signal "don't store me"
    private let sensitiveTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),  // passwords
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),  // ephemeral data
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    // Marker written alongside every copy-back so poll() can reliably skip it
    private let internalCopyMarker = NSPasteboard.PasteboardType("com.espaste.internal-copy")
    private let storageURL: URL = documentsDirectory.appendingPathComponent("ClipboardHistory.json")

    private init() {
        load()
        lastChangeCount = NSPasteboard.general.changeCount
        startMonitoring()
    }

    private func startMonitoring() {
        Timer.publish(every: 0.5, on: .main, in: .common)
            .autoconnect()
            .sink { [weak self] _ in self?.poll() }
            .store(in: &cancellables)
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        // Skip copies we made ourselves
        if skipNextChange {
            skipNextChange = false
            return
        }

        let currentTypes = Set(pb.types ?? [])

        // Skip if the internal marker is still present (belt-and-suspenders)
        guard !currentTypes.contains(internalCopyMarker) else { return }

        // Respect the nspasteboard.org privacy convention
        guard currentTypes.isDisjoint(with: sensitiveTypes) else { return }

        guard let text = pb.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        else { return }

        // Skip if identical to the most recent entry
        guard items.first?.text != text else { return }

        let frontApp = NSWorkspace.shared.frontmostApplication
        let item = ClipboardItem(
            id: UUID(),
            text: text,
            timestamp: Date(),
            appBundleID: frontApp?.bundleIdentifier,
            appName: frontApp?.localizedName,
            isFavorite: false,
            contentType: ClipboardStore.detectContentType(text)
        )

        items.insert(item, at: 0)
        if items.count > maxItems {
            items = Array(items.prefix(maxItems))
        }
        save()
    }

    // Copies item text back to the system clipboard without triggering a new history entry.
    func copyToClipboard(_ item: ClipboardItem) {
        skipNextChange = true
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(item.text, forType: .string)
        pb.setString("1", forType: internalCopyMarker)
        lastChangeCount = pb.changeCount
    }

    // Copies several items at once (newline-joined) without creating a new history entry.
    func copyToClipboard(_ multiple: [ClipboardItem]) {
        guard !multiple.isEmpty else { return }
        skipNextChange = true
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(multiple.map(\.text).joined(separator: "\n"), forType: .string)
        pb.setString("1", forType: internalCopyMarker)
        lastChangeCount = pb.changeCount
    }

    func delete(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        save()
    }

    func delete(ids: Set<UUID>) {
        items.removeAll { ids.contains($0.id) }
        save()
    }

    func toggleFavorite(_ item: ClipboardItem) {
        guard let idx = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[idx].isFavorite.toggle()
        save()
    }

    func clearAll() {
        items.removeAll { !$0.isFavorite }
        save()
    }

    private func save() {
        let url = storageURL
        let snapshot = items
        DispatchQueue.global(qos: .background).async {
            if let data = try? JSONEncoder().encode(snapshot) {
                try? data.write(to: url)
            }
        }
    }

    private func load() {
        guard let data = try? Data(contentsOf: storageURL),
              let decoded = try? JSONDecoder().decode([ClipboardItem].self, from: data)
        else { return }
        // Retroactively classify items that predate contentType (they default to .text)
        items = decoded.map { item in
            guard item.contentType == .text else { return item }
            let detected = ClipboardStore.detectContentType(item.text)
            guard detected != .text else { return item }
            var updated = item
            updated.contentType = detected
            return updated
        }
    }

    // NSDataDetector checks whether the ENTIRE trimmed string is a URL.
    static func detectContentType(_ text: String) -> ClipboardItem.ContentType {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty,
              let detector = try? NSDataDetector(types: NSTextCheckingResult.CheckingType.link.rawValue)
        else { return .text }
        let range = NSRange(trimmed.startIndex..., in: trimmed)
        let matches = detector.matches(in: trimmed, range: range)
        // Exactly one match covering the full string → it's a pure URL
        if matches.count == 1, let match = matches.first, match.range == range {
            return .url
        }
        return .text
    }
}

